### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by liammulh** [ClinGen/stanford-hci#1]
# HCI Roadmap

This issue serves as a roadmap / to-do list for the development of the HCI.

- Each level-2 header (`##`) is an epic.
    - 🔜 denotes a to-do epic.
    - 🔛 denotes an in-progress epic.
    - ✔️ denotes a finished epic.
- Each level-3 header (`###`) is a project.
    - 🔴 denotes a to-do project.
    - 🟠 denotes an on-hold project.
    - 🟡 denotes an in-progress project.
    - 🟢 denotes a finished project.

If a project is on hold, there *must* be a justification for putting it on hold beneath the project's header.

### 🟢 Create Plan for Software

- Use Django as a web framework.
- Use Django's built-in HTML templating.
- Use Postgres as a database.
- Use HTMX.
- If necessary, use Alpine.js or React for extra interactivity.

### 🟢 Create Plan for Infrastructure

Infrastructure code is housed in a [separate repository](https://github.com/ClinGen/stanford-infra).

- Use Terraform to create/destroy resources.
- Use ECS and ECR for the application code.
- Use CloudWatch for monitoring.
- Use GitHub Actions for deployment.

### 🟢 Create Wireframes

- [x] Create wireframes
    - [SVG wireframes file](https://github.com/ClinGen/stanford-hci/blob/main/doc/img/wireframes.svg)
    - [Excalidraw JSON file](https://github.com/ClinGen/stanford-hci/blob/main/doc/img/wireframes.excalidraw)

### 🟢 Create Data Model

- [x] Create a data model
    - [SVG data model file](https://github.com/ClinGen/stanford-hci/blob/main/doc/img/data-model.svg)
    - [Lucidchart link](https://lucid.app/lucidchart/64b3fdf3-67c2-4f4b-9c32-7d1b512fd3e8/edit?viewport_loc=-518%2C479%2C2767%2C1745%2C_AJWnx.Zl7yC&invitationId=inv_95e98b18-2e9f-4806-9b2a-e4caf4ca5f88)

### 🟢 Learn Terraform and Ansible

- [x] Learn and experiment with Terraform
- [x] Learn and experiment with Ansible

### 🟢 Set up Infra Repo

- [x] Create infrastructure repository
    - See the infra repo [here](https://github.com/ClinGen/stanford-infra).
- [x] Create scripts for IaC code quality
    - See the `check` script [here](https://github.com/ClinGen/stanford-infra/blob/main/tasks.py).

### 🟢 Dockerize the HCI code

I went in circles here for a while, but eventually managed to Dockerize the app without needing Docker Compose.

- [x] Create Dockerfile for the HCI
- [x] Build and test the Docker image in CI

### 🟢 Create AWS Resources on the Stanford AWS Account

See the tutorial I'm following for this [here](https://testdriven.io/blog/deploying-django-to-ecs-with-terraform/).

- [x] Create the Terraform for ECR
- [x] Push Docker image to ECR
- [x] Create the Terraform for networking
- [x] Create the Terraform for security groups
- [x] Create the Terraform for load balancers, listeners, and target groups
- [x] Create the Terraform for IAM roles and policies
- [x] Create the Terraform for ECS
- [x] Create the Terraform for health checks and logs
- [x] Create the Terraform for auto-scaling
- [x] Create the Terraform for outputs
- [x] Add health check code to Django app
- [x] Create the Terraform for RDS
- [x] Set up the subdomain
- [x] Set up allowed hosts

### 🟠 Deploy HCI

(Waiting to build production AWS resources until we're done with development.)

- [x] Tidy up run script
- [x] Document HCI infrastructure
- [x] Document HCI deployment process
- [x] Build test infrastructure
- [ ] Build production infrastructure (on hold until we're closer to being done)
- [x] Create script to deploy HCI to test server
- [x] Create script to deploy HCI to production server
- [x] Write issue describing HTTPS issue
- [ ] Get HTTPS working

### 🟢 Run Code Quality Checks

- [x] Create GitHub Actions workflow that formats, lints, type checks, and runs tests when a PR is opened

## 🔛 Add Functionality

See the [wireframes](https://github.com/ClinGen/stanford-hci/blob/main/doc/img/wireframes.svg).

### 🟢 Create the Score Calculator

See the [score template](https://docs.google.com/spreadsheets/d/14EQ56FxvYaVE4dUBOhnaZhD2Mf5IlQhSN8VzhD5Z0Bs/edit?gid=0#gid=0).

- [x] Create steps data
- [x] Create a data validator
- [x] Create the score calculator
- [x] Add steps, validator, and calculator for step 1
- [x] Add steps, validator, and calculator for step 2
- [x] Add steps, validator, and calculator for step 3
- [x] Add steps, validator, and calculator for step 4
- [x] Add steps, validator, and calculator for step 5
- [x] Add steps, validator, and calculator for step 6

### 🟠 Add Basic Pages and Functionality

This project is on hold while I work on infrastructure.

- [x] #29
- [ ] #30 (on hold until other pages are added)
- [x] Create sign up page and associated functionality
- [ ] Create curator profile page where a curator can change their username, email, password, institution, affiliation, etc. (on hold until we get Firebase working)
- [ ] Make sure a curator can reset their password if they've lost it (on hold until we get Firebase working)
- [ ] Add info to the right hand side of the navbar (email, log out link, help link, current affiliation, curator profile link)

### 🟡 Add "All" Pages

- [ ] Create the all curations page and associated functionality
- [ ] Create the all diseases page and associated functionality
- [ ] Create the all alleles/haplotypes page and associated functionality
- [ ] Create the all publications page and associated functionality

### 🔴 Add "New" Pages

- [ ] Create the new curation page and associated functionality
- [ ] Create the new disease page and associated functionality
- [ ] Create the new allele page and associated functionality
- [ ] Create the new publication page and associated functionality

### 🔴 Add Curation Pages

- [ ] Create the curation overview page and associated functionality
- [ ] Create the curation edit page and associated functionality

## 🔜 Miscellaneous Tasks

- [ ] Move score calculator to its own repo?
- [ ] Publish score calculator on PyPI?
- [ ] Use Sphinx for docs?
- [x] #33
- [ ] #32
- [ ] Conform to Gecko best practices
- [ ] Add repo to OpenSSF
- [ ] Work on OpenSSF compliance

## Q&A

Here's an [issue](https://github.com/ClinGen/stanford-hci/issues/31) where I collect questions and (hopefully) answers to them.
